// <auto-generated />
using DeviceEndpoint.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CalculEngineEndpoint.Migrations
{
    [DbContext(typeof(CalculContext))]
    [Migration("20190701114412_InitialCreate6")]
    partial class InitialCreate6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeviceEndpoint.Repositories.Calcul", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("average");

                    b.Property<string>("date");

                    b.Property<int>("domain_id");

                    b.Property<float>("max");

                    b.Property<float>("min");

                    b.Property<float>("sum");

                    b.Property<string>("type");

                    b.HasKey("id");

                    b.ToTable("Calcul");
                });
#pragma warning restore 612, 618
        }
    }
}
